// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const PrimitiveTypeEnum = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * Enum containing possible primitive types
 */
export type PrimitiveTypeEnum = (typeof PrimitiveTypeEnum)[keyof typeof PrimitiveTypeEnum];
